name: Generate Snake

on:
  schedule:
    - cron: "0 3 * * *"   
  workflow_dispatch:       
  push:
    branches: ["main"]     

permissions:
  contents: write          

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Generate snake SVGs
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: lucianoVillanuevaR
          outputs: |
            output/snake.svg
            output/snake-dark.svg?palette=github-dark

      - name: Commit & push
        run: |
          mkdir -p output
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add -A
          git commit -m "chore: update snake svg" || echo "No changes to commit"
          git push
